# Generated by Django 5.0.6 on 2024-06-29 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('id_ayuda', models.AutoField(db_column='idAyuda', primary_key=True, serialize=False)),
                ('ayuda', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('marca_producto', models.CharField(max_length=20)),
                ('valor_producto', models.CharField(max_length=6)),
                ('id_ayuda', models.ForeignKey(db_column='idAyuda', on_delete=django.db.models.deletion.CASCADE, to='animales.ayuda')),
            ],
        ),
    ]
